#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

gpsd -n -G -b /dev/ttyUSB0

python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
