# Generated by Django 2.2.7 on 2020-03-17 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('stars', models.ManyToManyField(to='api.Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('file', models.TextField()),
                ('loc_long', models.DecimalField(decimal_places=5, max_digits=10)),
                ('loc_lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ManyToManyField(to='api.Session')),
            ],
        ),
    ]
