# Generated by Django 2.2.7 on 2020-03-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField()),
                ('loc_long', models.DecimalField(decimal_places=5, max_digits=10)),
                ('loc_lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ManyToManyField(to='api.Session')),
            ],
        ),
    ]
