# Generated by Django 2.2.7 on 2020-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.RemoveField(
            model_name='session',
            name='note',
        ),
        migrations.AddField(
            model_name='session',
            name='loc_lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='loc_long',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
