# Generated by Django 2.2.7 on 2020-04-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200401_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
