# Generated by Django 2.2.7 on 2020-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FilePathField(max_length=400),
        ),
    ]
